# -*- coding: utf-8 -*-
"""module_2_codomax_internship

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xyMqbueVbKC02K_YYHBWP8wZZ_hOpqiO

**CALCULATOR BY USING IF,ELIF,IF**
"""

#calculator by using (if elif else )
first_value=int(input("enter a number: "))
second_value=int(input("enter another number: "))
operator=input("enter an operator: ")
#using if else function
if operator=="+":
  result=first_value + second_value
elif operator=="-":
  result=first_value - second_value
elif operator=="*":
  result=first_value * second_value
elif operator=="/":
  if second_value!=0:
    result=first_value / second_value
  else:
    result="cannot divide by 0"
else:
  result="invalid operator"
print(f"{result}")

"""**CALCULATOR BY CREATING DICTIONARY**"""

import operator as op #operator is already a builtin function so i call that function by using another name as op
first_value=int(input("enter a number: "))
second_value=int(input("enter another number: "))
operator=input("enter an operator: ")
#now making dictionary
ops_dict={
    '+': op.add,
    '-': op.sub,
    '*': op.mul,
    '/': op.truediv,
    }
result=ops_dict[operator](first_value,second_value)
print(f"{result}")

"""**GUESSING GAME**"""

using if ,elif,if only one time code runs

"""logic will be 1.computer will select a random number
2.user will try to guess the number by entering the number
then if the guess is correct print correct if guess is too low print low if guess is too high print high and user will guess the number until the answer is correct."""
import random
# a random number from range 1 to 100 is selected by computer
# number to be guessed
number=random.randint(1,100)
guess=int(input('enter a number'))
if number==guess:
  print('correct guess')
elif number>guess:
  print('guess is too low')
else:
  print('number is too high')

"""**if i want correct answer anyhow at the end then i will use while loop which runs until the correct guess is made**

**GUESSING GAME USING WHILE LOOP**
"""

import random
# a random number from range 1 to 100 is selected by computer
# number to be guessed
number=random.randint(1,10)
guess=int(input('enter a number'))
while guess!=number:
  print('incorrect guess')
  if guess>number:
    print('guess is high')
  else:
    print('guess is low')
  guess=int(input('try one more time: '))
print('correct guess\n you win')

"""**STUDENT GRADE CALCULATOR:**"""

marks=float(input('enter the marks out off 100: '))
if marks>=90 and marks<=100:
  print('A grade')
elif marks<90 and marks>=80:
  print('B grade')
elif marks<80 and marks>=70:
  print('C grade')
elif marks<70 and marks>=60:
  print('D grade')
else:
  print('F grade')